spring:
  datasource:
    username: dev
    password: dev123
    url: jdbc:mysql://127.0.0.1:3306/dev?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      register-mbeans: true

